name: mcurl
channels:
  - defaults
dependencies:
  - python=3.6
  - pytorch
  - torchvision
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pillow=6.1
  - seaborn=0.8.1
  - pandas
  - pip:
    - termcolor
    - git+https://github.com/deepmind/dm_control.git
    - git+https://github.com/denisyarats/dmc2gym.git@06f7e33
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - torchvision
    - scikit-image