name: mcurl
channels:
  - defaults
dependencies:
  - python=3.6
  - absl-py
  - pyparsing
  - pillow=6.1
  - seaborn=0.8.1
  - pandas
  - nvidia::cudatoolkit=9.2
  - pytorch::pytorch==1.7.1
  - pytorch::torchvision==0.8.2
  - pip:
    - termcolor
    - git+https://github.com/deepmind/dm_control.git
    - git+https://github.com/denisyarats/dmc2gym.git@06f7e33
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - scikit-image